### ISSUE TITLE
Working with Vercel but not Azure Static Web

### ISSUE THREAD

**Issue by improwise** [chihab/dotenv-run#107]
For whatever reason it seems like when running on an Azure Static Web app, the env variables can not be found, but on Vercel it works fine. 

Just to test it out more easily, I created a simple app to show movies from TMDB and deployed it to Vercel and Azure Static Web App. Running locally (with a .env) it works fine, and also running on Vercel with the env. variable defined, but on Azure I always get

`Cannot read properties of undefined (reading 'NG_APP_TMDB_API_KEY')`

Code is obviously exactly the same as it is being deployed from a GitHub repo, and in both Vercel and Azure I have defined it as an environment variable in the same way. 

Are there some special requirements on how to define environment variables in Azure to get this to work like special naming convention etc?

Thanks.

**Comment by improwise** [comment]
Some extra info:

Installed using

`ng add @ngx-env/builder`

and then I read the value in environment.ts (at least tries to)

```
export const environment = {
  production: false,
  tmdbApiKey: import.meta.env['NG_APP_TMDB_API_KEY'],
  tmdbApiUrl: 'https://api.themoviedb.org/3',
};


```

**Comment by improwise** [comment]
This seem to be related

https://github.com/vitejs/vite/discussions/13443

**Comment by improwise** [comment]
Can confirm that this seem to work, perhaps should be included somewhere in the documentation if more people run into this 

https://learn.microsoft.com/en-gb/azure/static-web-apps/build-configuration?tabs=github-actions#environment-variables

In this particular case, it meant adding this to the YAML file

```
env:  
          NG_APP_TMDB_API_KEY: mysupersecretkey
```

Not an ideal solution if you have secrets and your repo is public though so use care if that is the case...

**Comment by chihab** [comment]
All good then :)

Regarding security, keep in mind that those secret keys would end up in your JS code anyways.

As for the pipeline, you might want to make them as secured variables (check how it works in Azure) then only reference their name in your template file.

**Comment by improwise** [comment]
Yes :)

I guess you probably meant how it works in GitHub as it seems like it has to be part of the build rather than runtime. I would imagine that is how it works with Vercel as well, even though they kind of make it look like runtime variables in their UI. 

Even knowing that everything frontend is visible, it still feels better if you at least can't see it in the source code development time :)
