### ISSUE TITLE
Error with Runtime Environment Variables

### ISSUE THREAD

**Issue by Ionito** [chihab/dotenv-run#109]
Hello
We are using @nx to run several angular apps.
Now we need to configure dynamics envars to use the same docker image to run in differents enviroments.
We follow your docs, It works great until we set the `"runtime": true` in the options at our `project.json`
After adding this line we can't read in the app the already defined vars in the .env
Neither we see the expected generated file `ngx-env.js` in the **dist** folder.
Any idea?
Thanks in advance

**Comment by chihab** [comment]
Hey, are you using webpack builder? if yes see https://github.com/chihab/dotenv-run/issues/102#issuecomment-2462978730,  If not would it be possible to provide a reproducing repo? (I'll try to have a look tomorrow)

**Comment by Ionito** [comment]
yes, is that, I am using a webpack builder :-(

**Comment by chihab** [comment]
v19 published, feel free to give it a try.

Nx does not support Angular v19 yet though.

**Comment by Ionito** [comment]
we migrated to esbuild to make the v18 work.
Anyway, I tested the v19 in my old codebase (webpack build) and it works fine  🥰
