### ISSUE TITLE
Angular 19 issues

### ISSUE THREAD

**Issue by hadeed85** [chihab/dotenv-run#112]
import.meta.env.YOUR_ENV_VAR is undefined when using ngx-env.js during runtime after migrating to Angular 19.

**Comment by chihab** [comment]
seems to work fine here https://stackblitz.com/edit/ngx-env-3ey8js

I'd appreciate if you can provide more info or ideally a repo or a stackblitz

**Comment by hadeed85** [comment]
Sorry my bad. I was still on "18.0.2". It seems to work fine with "19.02".
