### ISSUE TITLE
Running @ngx-env/builder with Angular 19 and Karma

### ISSUE THREAD

**Issue by iiceman40** [chihab/dotenv-run#113]
Hi,

I updated to Angular 19.0.1 and @ngx-env/builder to 19.0.2 today and got everything working... until I tried to run my tests. I then got this error:

`@ngx-env/builder: Karma builder is not supported yet due to a limitation in the Angular CLI, use jest instead`

I checked the documentation and found this line:

> Supports all Angular CLI commands (Karma is not supported on v19)

So I am wondering now if this is the final state or if I can expect things to work in a later version. Maybe someone can elaborate why this doesn't work anymore. Since Karama is still the default test runner even for Angular 19, I somehow expect this to work 😅

Do I really have to stop using Karma or dotenv-run to get my tests to run or should I just give it a bit time and wait for a later version where this might work again?

**Comment by chihab** [comment]
Hi, good question.

Short answer, wait for a later version where this might work again :)

I'll have a look over the weekend to see if Angular CLI plans to support this (may need to open an issue on their repo) or alternatively have a workaround (back to the old way if possible).

**Comment by chihab** [comment]
Opened an issue here: https://github.com/angular/angular-cli/issues/29003

Update: the issue has been labelled as a bug so we can expect a fix.

**Comment by iiceman40** [comment]
Great, thank you! 😊 👍

**Comment by chihab** [comment]
Should be working now with latest versions of Angular and @ngx-env/builder.

**Comment by iiceman40** [comment]
I got to try it again today and everything seems fine now. Thank you! 🙏 😊
