### ISSUE TITLE
Is there a recommended approach for handling non-string variables?

### ISSUE THREAD

**Issue by karmasakshi** [chihab/dotenv-run#115]
Hello,

I'm trying to set and read boolean variables. Since the output is always a string, I'm wondering if I should type-cast the variables on usage or is there a better approach. I couldn't find a boolean/number usage example on [NPM](https://www.npmjs.com/package/@ngx-env/builder).

![Screenshot - 2024-12-18 16-46-06](https://github.com/user-attachments/assets/3f9f9e95-7ebf-45ea-8194-c04d43c87831)

```typescript
// env.d.ts

// Define the type of the environment variables.
declare interface Env {
  readonly NG_APP_URL: undefined;
  readonly NG_APP_IS_LOGGING_ENABLED: boolean;
  readonly NODE_ENV: string;
}

declare interface ImportMeta {
  readonly env: Env;
}
```

```typescript
// .env

NG_APP_URL=
NG_APP_IS_LOGGING_ENABLED=false
```

```typescript
// Code

console.log(typeof import.meta.env.NG_APP_URL + ' ' + import.meta.env.NG_APP_URL) // string ''
console.log(typeof import.meta.env.NG_APP_IS_LOGGING_ENABLED + ' ' + import.meta.env.NG_APP_IS_LOGGING_ENABLED) // string 'false'

if (import.meta.env.NG_APP_IS_LOGGING_ENABLED) {
  // This runs because 'false' == true and TypeScript doesn't complain about
  // the condition not being explicit (x === y) because the expected type is boolean
}
```

I'm on Angular 18.2.13 and @ngx-env/builder 18.0.2.

**Comment by chihab** [comment]
Since environment variables are always strings you should  indeed cast them to the JS type "manually".

I would suggest to use zod for that, it is commonly used to validate Environment variables values.

```ts
import z from 'zod';
const boolSchema = z.enum(['true', 'false']).transform((v) => v === 'true');

@Component({
  ...
})
export class AppComponent {
  sentry = boolSchema.parse(import.meta.env['NGX_SENTRY']);
}
```

**Comment by chihab** [comment]
I am considering whether a provided validation/conversion logic like the one here https://create.t3.gg/en/usage/env-variables would make sense for this package

**Comment by karmasakshi** [comment]
Thanks for your reply @chihab, I'll mark them as strings in env.d.ts so TypeScript warns me when I use them incorrectly. I'm happy to close the issue.

Regarding your proposal to add validations to the package, for your reference, here's one I've used before: https://www.npmjs.com/package/envalid.
