### ISSUE TITLE
hierarchical cascading not working if turbo.json in sub-module  

### ISSUE THREAD

**Issue by xmlking** [chihab/dotenv-run#14]
If I have `turbo.json` workspace root directory and  in sub-module `apps\goo` hierarchical cascading not working 

after deleting  `apps\goo\turbo.json`,  it functions as expected. 
<img width="758" alt="image" src="https://github.com/chihab/dotenv-run/assets/627951/bfda460b-37e7-479d-9541-60de953139a4">

it is valid to have    per-subproject `turbo.json`
https://turbo.build/repo/docs/core-concepts/monorepos/configuring-workspaces

**Comment by chihab** [comment]
How do you think we can differentiate between turbo.json file inside app/goo and the root one?

A workaround would be: `dotenv-run -r ../.. -e prod -- bash -c 'echo "$API_USERS"'`

**Comment by xmlking** [comment]
Nested turbo will alway have 	"extends": ["//"],
https://github.com/xmlking/spectacular/blob/8cea23c0426e5910355b40a3242d9945811ebec8/apps/web/turbo.json#L3C10-L3C10

**Comment by chihab** [comment]
Available in v1.2.3.

Thanks @xmlking for your contribution.
