### ISSUE TITLE
Support Multiple  Custom .env files

### ISSUE THREAD

**Issue by xmlking** [chihab/dotenv-run#15]
Support Multiple .env files like [dotenv-cli](https://github.com/entropitor/dotenv-cli)

> Multiple .env files can be specified, and will be processed in order:
```
dotenv -e .env3 -e .env4 <command with arguments>
```

I have two files (`.env` & `.secrets`) in each nested directories . I want to load both in the order.

**Comment by xmlking** [comment]
Proposing following CLI options to allow multiple custom .env files
Inspired by [Node.js 20.6.0](https://nodejs.org/en/blog/release/v20.6.0?ref=browsee.io) `.env` feature. 
```
dotenv-run -e prod   --env-file=.env  --env-file=.env=.sectets -- bash -c 'echo "✨ $API_USERS"'
# short 
dotenv-run -e prod   -f=.env  -f=.env=.sectets -- bash -c 'echo "✨ $API_USERS"'
```

I can do a PR if you agree. 
Thanks

**Comment by chihab** [comment]
Thanks for the suggestion.

What would be the hierarchical cascading logic in that case?

**Comment by xmlking** [comment]
> What would be the hierarchical cascading logic in that case?

It should work same way like hardcoded   `.env` file with hierarchical cascading logic.  

If no `--env-file` option  is specified, defaults to  `.env` file process as before.

if `--env-file=.env.vault` option  is specified,  both    `.env` and `.env.vault` files loaded along with `.env.vault${ENV}` and `.env.vault${ENV}.local`  etc in hierarchy.

Basically we can create a `Set` with populated with `.env` value and add all use supplied   `--env-file` to it.
Then, use that `Set` in place of  hardcoded   `.env` 

dotenv-run -e prod     -f=.env=.sectets -- bash -c 'echo "✨ $API_USERS"'
<img width="631" alt="image" src="https://github.com/chihab/dotenv-run/assets/627951/f29206e0-1e8c-4ca4-9acf-6b46c8ba9a6d">

**Comment by chihab** [comment]
Sounds good.

Thanks for your efforts @xmlking!
