### ISSUE TITLE
Add browser-esbuild builder

### ISSUE THREAD

**Issue by Klaster1** [chihab/dotenv-run#79]
Motivation:
The `application` builder always creates `browser` dir in the build target directory, breaking the deployment pipeline. [The official recommended way](https://github.com/angular/angular-cli/issues/26304#issuecomment-1817233019) is to use the `browser-esbuild`, however, dotenv-run doesn't wrap that particular builder.

Suggestion:
Wrap and expose the `browser-esbuild` builder in the same manner as the `application` builder.

**Comment by Klaster1** [comment]
OK, I am stupid for not reading until the thread end. [The desired result can be achieved](https://github.com/angular/angular-cli/pull/26675) with @angular-devkit/build-angular 17.1. Sorry for bothering you, close the issue if you feel like it.

**Comment by chihab** [comment]
Hey thanks for the feature request.
browser-esbuild target is available in @ngx-env/builder@17.2.2
