### ISSUE TITLE
how to apply  Env Vars  to multiple npm scripts

### ISSUE THREAD

**Issue by xmlking** [chihab/dotenv-run#80]
Recently I needed to run two scripts `svelte-kit sync`  & `vite dev`  and pass `Env Vars` to second command. 

This works 
```json
"scripts": {
   "dev": "dotenv-run -v -f .env -f .secrets -- vite dev"
}
```

This didn't work. `Env Vars` are not passed to  `vite dev` command
```json
"scripts": {
   "dev": "dotenv-run -v -f .env -f .secrets -- svelte-kit sync && vite dev"
}
```

any recommendations to accomplish this?

**Comment by chihab** [comment]
```dotenv-run -v -f .env -f .secrets -- bash -c 'svelte-kit sync && vite dev'```?

or have a npm script:

```
"scripts": {
   "dev:run": "svelte-kit sync && vite dev",
   "dev": "dotenv-run -v -f .env -f .secrets -- npm run dev:run"
}
```

**Comment by xmlking** [comment]
Second one should work for both windows and Mac 
b.t.w `-f .env,.secrets` did not work on windows. Have to rewrite `-f .env -f .secrets`

**Comment by chihab** [comment]
I'll close the issue, let me know if you need any help.
