### ISSUE TITLE
Angular Errors are swallowed with esbuild on the console.

### ISSUE THREAD

**Issue by DerAlbertCom** [chihab/dotenv-run#87]
Take the following component.

```
import {ChangeDetectionStrategy, Component} from '@angular/core';

@Component({
  selector: 'app-root',
  template: `<router-outlet /> {{ blah }}`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  blah ='';
}
```

`run ng serve`, everything is fine.

Now change `blah` in the template to `bla`, save. No Error in the CLI Console.

With the original dev-server builder from Angular, the errors shows up.

**Comment by chihab** [comment]
Fixed in latest update.
Could you please give it a try?

**Comment by DerAlbertCom** [comment]
Works! Thank you.

**Comment by DerAlbertCom** [comment]
Works! Thank you.
