### ISSUE TITLE
runtime: true fail

### ISSUE THREAD

**Issue by jhonnathanH** [chihab/dotenv-run#95]
recently implemented the property in 
angular.json
`... 
      "prefix":"NG", 
      "runtime": true. 
   ....`

but don't work properly, I used this version 
https://www.npmjs.com/package/@ngx-env/builder/v/17.3.0 with Angular 17.2.0

if this "runtime" is remove or false. the app works fine.

**Comment by chihab** [comment]
could you describe what's exactly not working?
